--CREATE TABLE

CREATE TABLE Persona (
    IdPersona NUMBER(14) PRIMARY KEY,
    Nombre VARCHAR2(64) NOT NULL,
    Ap1 VARCHAR2(64),
    Ap2 VARCHAR2(64),
    Tlf NUMBER(9),
    DNI VARCHAR2(9) UNIQUE NOT NULL
);

CREATE TABLE Cliente (
    IdCliente NUMBER(14) PRIMARY KEY,
    LicenciaConducir VARCHAR2(32),
    Persona_Id NUMBER(14),
    CONSTRAINT fk_cliente_persona FOREIGN KEY (Persona_Id) REFERENCES Persona(IdPersona) ON DELETE CASCADE
);

CREATE TABLE Sede (
    IdSede NUMBER(14) PRIMARY KEY,
    Nombre VARCHAR2(64) NOT NULL,
    Direccion VARCHAR2(128),
    Tlf NUMBER(9),
    TipoSede VARCHAR2(32),
    CONSTRAINT ck_tipo_sede CHECK (UPPER(TipoSede) IN ('FÍSICA','ON-LINE'))
);

CREATE TABLE Empleado (
    IdEmpleado NUMBER(14) PRIMARY KEY,
    Contrato VARCHAR2(64),
    Funcion VARCHAR2(64),
    Persona_Id NUMBER(14),
    Sede_Id NUMBER(14),
    CONSTRAINT fk_empleado_persona FOREIGN KEY (Persona_Id) REFERENCES Persona(IdPersona) ON DELETE CASCADE,
    CONSTRAINT fk_empleado_sede FOREIGN KEY (Sede_Id) REFERENCES Sede(IdSede) ON DELETE CASCADE
);

CREATE TABLE Marca (
    IdMarca NUMBER(14) PRIMARY KEY,
    Nombre VARCHAR2(64) NOT NULL,
    Historia VARCHAR2(256),
    SitioWeb VARCHAR2(128)
);

CREATE TABLE Modelo (
    IdModelo NUMBER(14) PRIMARY KEY,
    Nombre VARCHAR2(64) NOT NULL,
    FechaFabricacion DATE,
    LugarFabricacion VARCHAR2(64),
    TipoCombustible VARCHAR2(32),
    Precio NUMBER(8,2),
    CONSTRAINT ck_tipo_combustible CHECK (UPPER(TipoCombustible) IN ('GASOLINA','HÍBRIDO','ELÉCTRICO'))
);

CREATE TABLE Vehiculo (
    IdVehiculo NUMBER(14) PRIMARY KEY,
    Color VARCHAR2(32),
    Año NUMBER(4),
    NumeroSerie VARCHAR2(64) UNIQUE,
    IdMarca NUMBER(14),
    IdModelo NUMBER(14),
    IdOficina NUMBER(14),
    CONSTRAINT fk_vehiculo_marca FOREIGN KEY (IdMarca) REFERENCES Marca(IdMarca) ON DELETE CASCADE,
    CONSTRAINT fk_vehiculo_modelo FOREIGN KEY (IdModelo) REFERENCES Modelo(IdModelo) ON DELETE CASCADE
);

CREATE TABLE Alquiler (
    IdAlquiler NUMBER(14) PRIMARY KEY,
    FechaInicio DATE DEFAULT SYSDATE,
    FechaFin DATE,
    IdCliente NUMBER(14),
    IdEmpleado NUMBER(14),
    Sede_Id NUMBER(14),
    CONSTRAINT fk_alquiler_cliente FOREIGN KEY (IdCliente) REFERENCES Cliente(IdCliente) ON DELETE CASCADE,
    CONSTRAINT fk_alquiler_empleado FOREIGN KEY (IdEmpleado) REFERENCES Empleado(IdEmpleado) ON DELETE CASCADE,
    CONSTRAINT fk_alquiler_sede FOREIGN KEY (Sede_Id) REFERENCES Sede(IdSede) ON DELETE CASCADE
);


--INSERTS

CREATE SEQUENCE seqPersona START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999 NOCYCLE;

INSERT INTO Persona VALUES (seqPersona.NEXTVAL,'Juan','Pérez','Gómez',600111111,'11111111A');
INSERT INTO Persona VALUES (seqPersona.NEXTVAL,'María','López','Ruiz',600222222,'22222222B');
INSERT INTO Persona VALUES (seqPersona.NEXTVAL,'Carlos','Sánchez','Martín',600333333,'33333333C');

CREATE SEQUENCE seqCliente START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999 NOCYCLE;

INSERT INTO Cliente VALUES (seqCliente.NEXTVAL,'LIC-1111',1);
INSERT INTO Cliente VALUES (seqCliente.NEXTVAL,'LIC-2222',2);
INSERT INTO Cliente VALUES (seqCliente.NEXTVAL,'LIC-3333',3);

CREATE SEQUENCE seqSede START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999 NOCYCLE;

INSERT INTO Sede VALUES (seqSede.NEXTVAL,'Sede Centro','Madrid',911111111,'FÍSICA');
INSERT INTO Sede VALUES (seqSede.NEXTVAL,'Sede Norte','Bilbao',922222222,'FÍSICA');
INSERT INTO Sede VALUES (seqSede.NEXTVAL,'Web Central','Online',NULL,'ON-LINE');

CREATE SEQUENCE seqEmpleado START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999 NOCYCLE;

INSERT INTO Empleado VALUES (seqEmpleado.NEXTVAL,'Indefinido','Gestor',1,1);
INSERT INTO Empleado VALUES (seqEmpleado.NEXTVAL,'Temporal','Atención Cliente',2,2);
INSERT INTO Empleado VALUES (seqEmpleado.NEXTVAL,'Indefinido','Administrador',3,3);

CREATE SEQUENCE seqMarca START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999 NOCYCLE;

INSERT INTO Marca VALUES (seqMarca.NEXTVAL,'Toyota','Marca japonesa','www.toyota.com');
INSERT INTO Marca VALUES (seqMarca.NEXTVAL,'Tesla','Movilidad eléctrica','www.tesla.com');
INSERT INTO Marca VALUES (seqMarca.NEXTVAL,'Ford','Fabricante histórico','www.ford.com');

CREATE SEQUENCE seqModelo START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999 NOCYCLE;

INSERT INTO Modelo VALUES (seqModelo.NEXTVAL,'Corolla','01/01/20','Japón','GASOLINA',22000);
INSERT INTO Modelo VALUES (seqModelo.NEXTVAL,'Model 3','01/06/21','USA','ELÉCTRICO',42000);
INSERT INTO Modelo VALUES (seqModelo.NEXTVAL,'Kuga','01/03/19','España','HÍBRIDO',30000);

CREATE SEQUENCE seqVehiculo START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999 NOCYCLE;

INSERT INTO Vehiculo VALUES (seqVehiculo.NEXTVAL,'Blanco',2021,'SERIE001',1,1,1);
INSERT INTO Vehiculo VALUES (seqVehiculo.NEXTVAL,'Negro',2022,'SERIE002',2,2,2);
INSERT INTO Vehiculo VALUES (seqVehiculo.NEXTVAL,'Gris',2020,'SERIE003',3,3,1);

CREATE SEQUENCE seqAlquiler START WITH 1 INCREMENT BY 1 MAXVALUE 9999999999999999 NOCYCLE;

INSERT INTO Alquiler VALUES (seqAlquiler.NEXTVAL,'01/02/23','05/02/23',1,1,1);
INSERT INTO Alquiler VALUES (seqAlquiler.NEXTVAL,'10/02/23','15/02/23',2,2,2);
INSERT INTO Alquiler VALUES (seqAlquiler.NEXTVAL,'20/02/23','25/02/23',3,3,3);


--DROPS

DROP SEQUENCE seqPersona;
DROP SEQUENCE seqCliente;
DROP SEQUENCE seqSede;
DROP SEQUENCE seqEmpleado;
DROP SEQUENCE seqMarca;
DROP SEQUENCE seqModelo;
DROP SEQUENCE seqVehiculo;
DROP SEQUENCE seqAlquiler;

DROP TABLE Alquiler CASCADE CONSTRAINTS;
DROP TABLE Vehiculo CASCADE CONSTRAINTS;
DROP TABLE Modelo CASCADE CONSTRAINTS;
DROP TABLE Marca CASCADE CONSTRAINTS;
DROP TABLE Empleado CASCADE CONSTRAINTS;
DROP TABLE Cliente CASCADE CONSTRAINTS;
DROP TABLE Sede CASCADE CONSTRAINTS;
DROP TABLE Persona CASCADE CONSTRAINTS;